### ISSUE TITLE
IRIS containers do not start on Docker 20.10.14+ (Docker Desktop 4.8.1)

### ISSUE THREAD

**Issue by isc-gsaito** [intersystems-community/irisdemo-demo-fraudprevention#34]
I recently cloned this project and I tried to start the demo environment on my Win10 desktop with Docker Desktop and WSL2 Ubuntu. 

The IRIS based containers (datalake-1, bankingcore_1 and bankingtrnsrv_1) where failing to start with the following errors: 

datalake_1           | [INFO] Writing status to file: /home/irisowner/irissys/iscagent.status
datalake_1           | Reading configuration from file: /home/irisowner/irissys/iscagent.conf
datalake_1           | ISCAgent[20]: Starting
datalake_1           | ISCAgent[21]: Starting ApplicationServer on *:2188
datalake_1           | [INFO] ...executed command /home/irisowner/irissys/startISCAgent.sh 2188
datalake_1           | [ERROR] Required Linux capability cap_setuid is missing.
datalake_1           | [ERROR] Required Linux capability cap_dac_override is missing.
datalake_1           | [ERROR] Required Linux capability cap_fowner is missing.
datalake_1           | [ERROR] Required Linux capability cap_setgid is missing.
datalake_1           | [ERROR] Required Linux capability cap_kill is missing.
datalake_1           | [FATAL] Your IRIS container is missing one or more required Linux capabilities.

The log above is from datalake_1, but all the others were showing the same error messages. 

To correct the situation I applied the solution described in this post: 

https://community.intersystems.com/post/using-intersystems-iris-containers-docker-201014

So I changed the docker-compose.yml file to include the " --check-caps false" command statement: 

  datalake:
    init: true
    image: intersystemsdc/irisdemo-demo-fraudprevention:datalake-version-1.9.1
    hostname: datalake
    restart: on-failure
    **command: --check-caps false**
    ports:
    # 1972 is the superserver default port
    - "9095:1972"
    # 52773 is the webserver/management portal port
    - "9094:52773"
    volumes:
    - type: bind
      source: ./normalized_datalake/shared/
      target: /shared

Similar changes have to be applied on bankingcore_1 and bankingtrnsrv_1. 

After saving those changes on docker-compose.yml , I was able to start the demo environment.

**Comment by amirsamary** [comment]
Please, try again.

**Comment by isc-gsaito** [comment]
It works fine.
